# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libudev-dev
				- doxygen
				- graphviz
      env: COMPILER=g++-4.9

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libudev-dev
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - cd test
  - ctest  
  - cd ..
  - doxygen doxygen.conf
