sudo: required
dist: precise
language: cpp
matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
        - libudev-dev
        - doxygen
        - graphviz
    env: COMPILER=g++-4.9
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libudev-dev
script:
- export
- mkdir build
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
- cd test
- ctest
- cd ..
- ls
- doxygen doxygen.conf
- tar czvf libudev-docs.tar.gz docs
env:
  global:
    secure: cowTvUeEHYDLyk7dRPUFSk4gypke/t3Xut3juaEiv6rp2bFSktOfUGqGFwk8DVIH6yOaLhRwaNxWx9+u6AAtA9Ldzw9D9Nj6kuuLUW/wPu+m9vQUUDsI5fbJaEolWIo1pRUA2Cdn1L30sCopHWwCewqdn1khtU03a5jjWL7Mbf2pkeVRF/21A15IVKhAiYs+vTL8Ri2fL9eeUSXrGD200D82wrgapTc64NL2NEYR0cgggQlIjHhDnx9GxG2cpJ1qJDf4amlh8a9irUGPWT1nFApbBkgpumnsFFeuYzjWmi1nipJxJDMQg+aVGFqRUHt7P/aUJQmtm972zX6E9nuJwjcRLEIeHCWTyP03f6YIQWm5n4izvHML5GwXyg5swy82wqheQtc80TPpRrZxCFFi7XW9PrqSnrEAf3OPs5aISf+pRhlAM77YyE6zubgZuZ0C45U7Z8npA3gCLCQuxWDbG4ts0QMDbavAwO1OTjDaER/ISdIuVPZxu472otF194JdNymkLsPoIPKyyLcQh3UZZpWmNE0vGRB21J/SYQbE6frbLmlj3+rRzO3DOus0geDaGIKJyyIFVUQU14YQgVZVriNqhGoYYLP0Kzb7UX03rlP90rxDR5vNPjioKQtxfisN7bOveAn8pXRsdGON9IBhAOnmYklYXyKmr3Q2De9ecUo=
deploy:
  provider: releases
  api_key:
    secure: c3dA1fYDANBwfppeJUNvZeLmePr+LOGgMLW/TFm+mxedCTjUzZj9PBXgF7Nhm+llSk2u4Gui3M30UMpBLd6VeWyPitlPfel9iPYuDpymC/x3BeYeyC4g6hie39EeinZ78yd+ekZQN772s9McxuGkjYDZi/BMyGSNR34l3XpT6aKbvyv/OFdVhcronYIADH9wFwlLefEQT+0U/5s/c6pkLOgMyF9xYrVi8OdhyM2DCzX99gYzktR2Zw2V0CcKWZL/1X8fdBt1tHztRiMA7hOuA+XkGElGTrftlxhq9H/C2/75aN2pYRiRNXArT3Td6f/UKL5Z8kFvGigMVs1eY//hgwCQi+3LT+Jg3qxL/Xias0MV6nZsd3dPOBSK+O6hJp3vCsc4SeokxgaqA8gu+aWW+P0h9PdFdos4/0K80fXkbL1Mj7tOtFpIVdQ3+rcDOla/U4M2osUq4bdv7xYn0Qdf10+uZrgq+8x6O3Z+Z4pkD16i+1PikjTM4qa8fTcOIPG3DceEMo53xPwwMhMFARZ9kzEg7XSa4Zleer8Q/Iq63p3bCrINbPSzMuD/XljH23ra3srqMpCftxnlg3nbNkkg4vaPgaHjAqD+yNW2i1JbWsEix8SQ+MFFJZY3y/IkAkpMGMg48lDzX2O+0q6OlvKMrHM0+MurtLcdsB05o+AGZAg=
  file: libudev-docs.tar.gz
  on:
    repo: ElFeesho/libudevpp
