language: cpp

include:
  - compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
          - libudev-dev
    env: COMPILER=g++-5

install:
    - export CXX="g++-5" CC="g++-5"

script:
  - cmake .
  - make
  - cd test
  - ctest
  

