language: cpp

compiler:
  - g++

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y cmake libudev-dev; fi

script: cmake .; make

after_success:
  - echo Success

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
