language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libudev-dev
      env: CMAKE_CXX_COMPILER=g++-4.9

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd test
  - ctest
  

