language: cpp

sudo: required
dist: trusty

include:
  - compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
    env: COMPILER=g++-4.9

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd test
  - ctest
  

