language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libudev-dev
      env: COMPILER=`g++-4.9`

script:
  - export COMPILER=`which $COMPILER`
  - ./ci.sh  

